const FETCH_USERS = 'FETCH_USERS'
const CLEAR_USERS = 'CLEAR_USERS'
const SET_USERS = 'SET_USERS'
const ADD_USER = 'ADD_USER'
const CHANGE_INPUT_VALUE ='CHANGE_INPUT_VALUE'
 export {FETCH_USERS, CLEAR_USERS, SET_USERS, ADD_USER, CHANGE_INPUT_VALUE}